### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by mightytry** [mightytry/PictureToPC#1]
- [x] Better image compression
- [x] Redo button
- [ ] Better contrast
- [ ] Paste own Pictures

**Comment by mightytry** [comment]
- [x] Fix that Code goes away after restart in app
- [x] Fix error if config empty
- [x] Fix name Ip where code should stand in app
- [x] Hotspot

**Comment by mightytry** [comment]
- [ ] Fix on windows when wifi switches

**Comment by mightytry** [comment]
- [ ] Auto update Updater
- [ ] Auto update APK
- [ ] Fix Updater that it resets to V0 without connection
- [ ] Username
- [ ] Autoconnect with devices nearby (Bluetooth)
- [ ] ping bei start nach 1sec abbrechen
